name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      LISP: sbcl-bin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Common Lisp Environment
        # This action will automatically detect your qlfile,
        # run 'qlot install', and cache the .qlot directory.
        uses: 40ants/setup-lisp@v4
        with:
          asdf-system: cl-lz4-rs

      - name: Run Tests
        shell: bash
        run: |
          make build
          echo "--> Running tests..."
          qlot exec ros --non-interactive \
              --eval '(push *default-pathname-defaults* asdf:*central-registry*)' \
              --eval "(asdf:test-system :cl-lz4-rs-tests)"

