name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      LISP: sbcl-bin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Common Lisp Environment
        uses: 40ants/setup-lisp@v4
        with:
          asdf-system: cl-lz4

      - name: Install Qlot
        run: ros install qlot

      - name: Install Dependencies and Run Tests
        shell: bash
        run: |
          # The 'make test' command automatically handles 'qlot install'
          # and runs the tests in a reproducible environment.
          make test
