name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      LISP: sbcl-bin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Common Lisp
        uses: 40ants/setup-lisp@v4

      - name: Install Dependencies & Run Tests
        shell: lispsh -eo pipefail {0}
        run: |
          # First, build the Rust native library as defined in the Makefile
          make build

          # Now, install dependencies manually using Roswell.
          echo "--> Installing dependencies with Roswell..."
          ros install cffi
          ros install fiveam
          ros install trivial-benchmark
          ros install salza2
          ros install chipz
          
          echo "--> Running tests..."
          # Use ros directly to load the system and run the tests.
          # We explicitly add the current directory to ASDF's central registry.
          ros --non-interactive \
              --eval "(push #P'./' asdf:*central-registry*)" \
              --eval "(asdf:test-system :cl-lz4-rs-tests)" \
              --quit
